# Generated by Django 5.0.4 on 2024-05-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_contract_validity_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
